name: ne_proj
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  url_launcher: ^5.7.2
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1+2
  flutter_bloc: ^6.0.5
  bloc: ^6.0.3
  equatable: ^1.2.5
  lottie: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen-Regular.ttf
